### ISSUE TITLE
[BUG]: Can not apply multiple rich style when typing

### ISSUE THREAD

**Issue by nhuthuynh195** [10play/10tap-editor#202] opened 2024-09-20 04:50 UTC
**Describe the bug**
I had try implement with library, but I face some issue when edit content, the issue is when typing I can not apply multiple rich style like video: https://drive.google.com/file/d/1vn6QQvlK2E-Tux0EVCH0OPzXYrLv5Rq5/view?usp=sharing, I use example code from lib and I use Vietnamese language for keyboard

**Comment by 17Amir17** [comment] 2024-09-25 17:52
Hey @nhuthuynh195,
Could you share your code?

**Comment by nhutph** [comment] 2024-09-26 03:03
@17Amir17 I just use sample code like this 
`
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import React from 'react';
import {
  SafeAreaView,
  KeyboardAvoidingView,
  Platform,
  StyleSheet,
} from 'react-native';
import { RichText, Toolbar, useEditorBridge } from '@10play/tentap-editor';

export const Basic = ({}: NativeStackScreenProps<any, any, any>) => {
  const editor = useEditorBridge({
    autofocus: true,
    avoidIosKeyboard: true,
    initialContent,
  });

  return (
    <SafeAreaView style={exampleStyles.fullScreen}>
      <RichText editor={editor} />
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={exampleStyles.keyboardAvoidingView}
      >
        <Toolbar editor={editor} />
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const exampleStyles = StyleSheet.create({
  fullScreen: {
    flex: 1,
  },
  keyboardAvoidingView: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
  },
});

const initialContent = `<p>This is a basic example!</p>`;
`

**Comment by nhutph** [comment] 2024-10-02 04:35
anyupdate for isssue ???

**Comment by nhutph** [comment] 2024-10-20 07:35
DEAD LIB, do not any support.

**Comment by GuySerfaty** [comment] 2024-11-13 07:00
hi @nhuthuynh195, @nhutph we just cannot reproduce your issue, let me add here a video that sows basic example with auto-correct on:

https://github.com/user-attachments/assets/3813a9e2-47e0-4b50-956e-f727118115a7

**Comment by GuySerfaty** [comment] 2024-12-11 13:18
Im going to close this issue feel free to re-open

**Closed by GuySerfaty** 2024-12-11 13:18 UTC
